#####################################################
# GREEDY: GG-RTP-SMC N=10 M=2 adaptive + argmax
# No importance weight correction
#####################################################

tag: ${prompt}
seed: 0
height: 512
width: 512

prompt: ""
negative_prompt: null
time_schedule: linear

model: "flux"
mini_batch_size: 1
grad_minibatch_size: 1
true_cfg_scale: 1.0
guidance_scale: 3.5

original_scheduler: linear
new_scheduler: vp
sample_method: sde
diffuse_coeff_func: rev_original
diffusion_norm: 1.0
save_vram: true

mcmc: pcnl
alpha_mcmc: 0.1
step_size: 0.5
num_mcmc_steps: 25
num_chains: 5
burn_in: 25
custom_call_function_name: chains_thinning
grad_norm: 0.0004
grad_const_scale: null
rho: null
mcmc_scheduler: uniform

runner: smc
alpha: 0.1
num_particles: 10
num_inference_steps: 25
ess_threshold: 0.5
smc_grad_norm: 0.0004
smc_grad_const_scale: null

return_max_reward: true
init_weight_method: reward
grad_scale: 1.0

method: rtp_smc
task_name: aesthetic
M: 2
eta: 1.0

adaptive_M: true
M_warmup_frac: 0.5

greedy_selection: true

decode_to_unnormalized: false
